import datetime

def main():
    now = datetime.datetime.now()
    # 以當下時間作為檔名，避免重覆
    filename = now.strftime("run-%Y%m%d-%H%M%S.md")
    
    content = f"""# GitHub Actions Run Log

- **Run time:** {now}
- **Description:** This file was auto-generated by GitHub Actions every 5 minutes.
"""

    with open(filename, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"Markdown file created: {filename}")

if __name__ == "__main__":
    main()
